# core/state_schema.py
from enum import Enum
from typing import List, Optional, Dict
from pydantic import BaseModel, Field

class WorkflowState(str, Enum):
    """
    The Rigid States of the Finite State Machine (FSM).
    """
    INITIAL = "INITIAL"                 # System start
    INGESTION = "INGESTION"             # PDF Processing
    DRAFTING = "DRAFTING"               # Analyst Agent working
    CRITIQUING = "CRITIQUING"           # Critic Agent reviewing
    AWAITING_HUMAN = "AWAITING_HUMAN"   # Waiting for user approval
    FINALIZED = "FINALIZED"             # Done
    ERROR = "ERROR"                     # Fallback state

class InvestmentMemo(BaseModel):
    """
    The structured output generated by the Analyst Agent.
    """
    company_name: str = Field(..., description="Name of the startup")
    executive_summary: str = Field(..., description="High-level summary of the deal")
    key_strengths: List[str] = Field(..., description="List of competitive advantages")
    risks: List[str] = Field(..., description="List of potential risks")
    verdict: str = Field(..., description="Preliminary investment verdict (Buy/Pass/Watch)")

class AuditResult(BaseModel):
    """
    The output from the Critic Agent.
    """
    is_verified: bool = Field(..., description="True if no hallucinations found")
    feedback: str = Field(..., description="Detailed feedback or list of hallucination corrections")
    score: int = Field(..., description="Confidence score 1-10")

class GlobalContext(BaseModel):
    """
    The 'God Object'. This is the payload passed between all steps.
    """
    state: WorkflowState = WorkflowState.INITIAL
    raw_pdf_text: Optional[str] = None
    current_draft: Optional[InvestmentMemo] = None
    audit_history: List[AuditResult] = Field(default_factory=list)
    retry_count: int = 0
    final_report: Optional[str] = None